const RECORDS = [
{title:'The two founding marriages', blurb:'St Mary’s Pro-Cathedral, ten years and one day apart.',
 items:[
  {h:'William Valentine & Martha Mackey — 3 August 1863', m:'Church register · Pro-Cathedral, Roman Catholic', imgs:['image3','image4'],
   cap:'Both parties are named with their fathers: William Valentine, railway clerk, of 93 Marlboro Street, and Patrick Mackey, coach maker, of 18 Greenville Street. He is “of full age”; she is a minor.',
   link:'https://www.irishgenealogy.ie/view/?record_id=707108e3c7-312'},
  {h:'William Valentine & Martha Mackey — civil return', m:'Civil registration · 1863', imgs:['image2'],
   cap:'The state’s copy of the same marriage. Names match, ages fit the 1901 census, professions fit, and the church fits the Catholic side of the family.',
   link:'https://www.irishgenealogy.ie/files/civil/marriage_returns/marriages_1863/09649/5499445.pdf'},
  {h:'James Kavanagh & Anne Walsh — 4 August 1873', m:'Church register and civil return', imgs:['image5','image6'],
   cap:'He is a railway guard and a widower at 26; she is a cloakmaker of 16, a minor. The civil copy spells the surname Cavanagh — the addresses and dates confirm it is the same event.',
   link:'https://www.irishgenealogy.ie/view/?record_id=707108e3c7-3444'}]},

{title:'Births and baptisms', blurb:'The documents that fix each person to a date, a street and a parish.',
 items:[
  {h:'Martha Herbert — 1846', m:'Baptism · possible identification for Martha Mackey', imgs:['image1'],
   cap:'The year is right for Martha Mackey based on her death certificate, and the sponsors were Patrick and Catherine Mackey — the names she gave as her parents at her wedding. The surname Herbert remains unexplained.',
   link:'https://www.irishgenealogy.ie/view/?record_id=c963d01f6e-9829'},
  {h:'Thomas Valentine — 18 April 1881', m:'Baptism · St George’s, Church of Ireland, Hardwicke Place', imgs:['image7'],
   cap:'Father William Valentine, bookbinder, of 31 Portland Place. No image of the civil birth registration survives — it may be corrupted, though the original could still be viewable in Dublin.',
   link:'https://www.irishgenealogy.ie/view/?record_id=19d58ec1c8-10756'},
  {h:'Anne Kavanagh — 13 March 1882', m:'Civil birth registration and Pro-Cathedral baptism', imgs:['image8','image9','image10','image11'],
   cap:'Father James Kavanagh, porter, of 128 Upper Abbey Street, recorded as illiterate; mother Annie Walsh. The only Anne Kavanagh born in 1881–83 with the right parents, the right district and the right church.',
   link:'https://www.irishgenealogy.ie/view/?record_id=5fc6443d7a-4683128'},
  {h:'Reuben John Valentine — 5 January 1888', m:'Civil birth registration', imgs:['image20','image19'],
   cap:'Father William Valentine, bookbinder; mother Martha Mary Valentine, formerly Markey; 30 Portland Place. This is the record that proved the Oxmantown Road census household was the right family.',
   link:'https://www.irishgenealogy.ie/view/?record_id=5fc6443d7a-3891754'},
  {h:'Reuben John Valentine — baptism', m:'St George’s, Church of Ireland, 1888', imgs:['image22','image21'],
   cap:'The parish register entry: parents William and Martha, abode 30 Portland Place, trade book-binder.',
   link:'https://www.irishgenealogy.ie/files/church/d-298-2-9-096.pdf'}]},

{title:'The marriage that joined the families', blurb:'5 August 1900, St Mary’s Pro-Cathedral.',
 items:[
  {h:'Thomas Valentine & Anne Kavanagh — church register', m:'Liber Matrimoniorum · Pro-Cathedral, 1900', imgs:['image13','image14'],
   cap:'The Latin marriage register of the Pro-Cathedral for 1900.',
   link:'https://www.irishgenealogy.ie/view/?record_id=76e681dcc3-5778'},
  {h:'Thomas Valentine & Anne Kavanagh — civil return', m:'Civil registration · 5 August 1900', imgs:['image15','image16'],
   cap:'Thomas Valentine, bachelor, of 30 Portland Place, father William Valentine. Annie Kavanagh, spinster, of 30 Denmark Street, father James Kavanagh. Witnesses Edward Moore and Lizzie Geeling; married by Augustine Farrell.',
   link:'https://www.irishgenealogy.ie/files/civil/marriage_returns/marriages_1900/10355/5769507.pdf'}]},

{title:'Deaths', blurb:'Two certificates that pin down the older generation.',
 items:[
  {h:'Martha Valentine — 10 July 1900', m:'Civil death registration · 30 Portland Place', imgs:['image12'],
   cap:'Aged 54, “Bookbinder’s Wife”, cause of death cardiac asthenia — heart exhaustion. Her husband is a widower by the following census, and the address and profession match exactly.',
   link:'https://www.irishgenealogy.ie/view/?record_id=0c9e5f72a2-3909054'},
  {h:'William Valentine — 29 December 1908', m:'Civil death registration · 27 Ross Street', imgs:['image25','image24'],
   cap:'Recorded as William Thomas Valentine, widower, 67, book-binder. Cause: phthisis pulmonalis, certified. Informant: “Thomas Valentine, son, present at death, 2 St Mary’s Terrace, Ballybough Road.” Note the year — the summary chart in the original spreadsheet gives 1906, but the certificate is unambiguously 1908.',
   link:'https://www.irishgenealogy.ie/view/?record_id=0c9e5f72a2-3184848'}]},

{title:'The census returns', blurb:'Three snapshots of the households in this tree — two Irish, one Scottish.',
 items:[
  {h:'1901 — Oxmantown Road, Arran Quay', m:'William Valentine, widower, 59, bookbinder', imgs:['image18'],
   cap:'The household: William 59 (Church of Ireland); Elizabeth 36, bookfolder (Wesleyan); Martha Byrne 31, widow, bookfolder (Roman Catholic); Hannah 22; Reuben 13; Mary 11; and granddaughter Martha Byrne, 3. Three religions under one roof.',
   link:'https://nationalarchives.ie/collections/search-the-census/census-record/?census_year=1901&surname__icontains=valentine&firstname__icontains=william&id=5200084'},
  {h:'1901 — Little Denmark Street, North City', m:'James Kavanagh, 54, general labourer', imgs:['image17'],
   cap:'James 54 and Anne 44, with sons James 17 (general labourer) and John 14 (scholar), plus a nephew, Patrick Walsh, 23, a plumber and gasfitter — and, unusually for this household, Church of Ireland.',
   link:'https://nationalarchives.ie/collections/search-the-census/census-record/?census_year=1901&surname__icontains=kavanagh&firstname__icontains=james&county=Dublin&religion_updated=Roman+Catholic&townland=Little+Denmark+Street&id=5190883'},
  {h:'1901 — 152 Great Britain Street, Rotunda', m:'Thomas Valentine, 19, book finisher', imgs:['image23'],
   cap:'Thomas 19, Annie 18, and William, aged 0. Married eight months, with a three-month-old son. Thomas is recorded as “R C Church” — despite his Church of Ireland baptism.',
   link:'https://nationalarchives.ie/collections/search-the-census/census-record/?census_year=1901&surname__icontains=valentine&firstname__icontains=thomas&id=5180096'},
  {h:'1911 — 22 Ballybough Road, Mountjoy', m:'Thomas Valentine, 29, foreman bookbinder finisher', imgs:['image26'],
   cap:'Ten years married; seven children born, six living. William 10, John T 7, Martha 5, Louis 4, Robert 2, Walter 1. The two eldest boys are recorded as speaking Irish and English.',
   link:'https://nationalarchives.ie/collections/search-the-census/census-record/?census_year=1911&surname__icontains=valentine&firstname__icontains=william&id=48711'},
  {h:'1911 — 13 Wood Lane, Arran Quay', m:'A possible sighting of Martha Byrne and her daughter', imgs:['image27'],
   cap:'A boarding house of laundresses and needlewomen. Martha Mary Byrne, 40, widow, nurse domestic, and Martha Lillian Byrne, 13, scholar — plausibly William’s daughter and granddaughter, ten years on from Oxmantown Road. Both are recorded as Protestant Church of Ireland, which is the puzzle.',
   link:'https://nationalarchives.ie/collections/search-the-census/census-record/?census_year=1911&surname__icontains=byrne&firstname__icontains=martha&age__gte=10&age__lte=19&id=471571'},
  {h:'1921 — the Wynd, Cumbernauld, Dunbartonshire', m:'Scotland, 19 June 1921 · schedule 139 · two rooms, fourteen people', imgs:['c1921_names'],
   cap:'Thomas Valentine, 40, head, born Dublin, Ireland; Annie E., 39; then ten children born in Ireland and two — Brendon, 2, and Mary, 8 months — born at Cumbernauld. Fourteen people in all. This single page adds two children to the tree and dates the emigration to between November 1915 and 1919.<br><br>It also tests the Dublin dates. The three eldest reconcile almost exactly: Thomas at 40 years 2 months, Annie at 39 years 3 months and William at 20 years 6 months fit 18 April 1881, 13 March 1882 and 20 December 1900 to within days. The younger children do not. Counting back from 19 June 1921, the enumerator has Robert 2 months old, Walter 3, Anne 4, Thomas 6 and Frank 7 months older than their birth certificates allow — and for Thomas and Anne that pushes them into the wrong year. Someone was reciting a large family’s ages from memory.',
   link:'https://www.scotlandspeople.gov.uk/'},
  {h:'1921 — what they were all doing', m:'Occupation and employer columns, same page', imgs:['c1921_occ'],
   cap:'Thomas: <b>Railway Porter</b>, North British Railway Co — the end of three generations in the book trade. William: brickworker, J. G. Stein &amp; Co Ltd. Thomas John: brickwork panman, Castlecary Fireclay Co. Martha: “Sheet Worker” (the reading is not certain), J &amp; A. Campbell &amp; Co., warehousemen. Annie E.: home duties. Louis and the six below him: scholars — seven in all.',
   link:'https://www.scotlandspeople.gov.uk/'},
  {h:'1921 — the full page', m:'Census 495/9/19, page 19 of 24 · Cumbernauld', imgs:['c1921_full'],
   cap:'The Valentines are schedule 139, lines 18 to 31. Their neighbours in the Wynd give the flavour of the place: two clay miners — one at J. G. Stein &amp; Co, one at the Castlecary Fireclay Co — an engineer’s fitter, a metal merchant, a clerkess, and a grocery assistant at the Cumbernauld Co-operative Society.',
   link:'https://www.scotlandspeople.gov.uk/'}]}
];
